export const ALL_CASES_FAIL = 'ALL_CASES_FAIL'
export const ALL_CASES_REQUEST = 'ALL_CASES_REQUEST'
export const ALL_CASES_SUCCESS = 'ALL_CASES_SUCCESS'

export const GET_CLIENTS_FAIL = 'GET_CLIENTS_FAIL'
export const GET_CLIENTS_REQUEST = 'GET_CLIENTS_REQUEST'
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'

export const GET_CLIENT_FAIL = 'GET_CLIENT_FAIL'
export const GET_CLIENT_REQUEST = 'GET_CLIENT_REQUEST'
export const GET_CLIENT_SUCCESS = 'GET_CLIENT_SUCCESS'

export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL'
export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST'
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS'

export const UPDATE_CLIENT_FAIL = 'UPDATE_CLIENT_FAIL'
export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST'
export const UPDATE_CLIENT_SUCCESS = 'UPDATE_CLIENT_SUCCESS'

export const GET_CASES_FAIL = 'GET_CASES_FAIL'
export const GET_CASES_REQUEST = 'GET_CASES_REQUEST'
export const GET_CASES_SUCCESS = 'GET_CASES_SUCCESS'

export const GET_CASE_FAIL = 'GET_CASE_FAIL'
export const GET_CASE_REQUEST = 'GET_CASE_REQUEST'
export const GET_CASE_SUCCESS = 'GET_CASE_SUCCESS'

export const CREATE_CASE_FAIL = 'CREATE_CASE_FAIL'
export const CREATE_CASE_REQUEST = 'CREATE_CASE_REQUEST'
export const CREATE_CASE_SUCCESS = 'CREATE_CASE_SUCCESS'

export const UPDATE_CASE_FAIL = 'UPDATE_CASE_FAIL'
export const UPDATE_CASE_REQUEST = 'UPDATE_CASE_REQUEST'
export const UPDATE_CASE_SUCCESS = 'UPDATE_CASE_SUCCESS'


export const CASES_FILES_FAIL = 'CASES_FILES_FAIL'
export const CASES_FILES_REQUEST = 'CASES_FILES_REQUEST'
export const CASES_FILES_SUCCESS = 'CASES_FILES_SUCCESS'

export const CASES_READ_IDS = 'CASES_READ_IDS'


