

export const GET_CASE_FAIL = 'GET_CASE_FAIL'
export const GET_CASE_REQUEST = 'GET_CASE_REQUEST'
export const GET_CASE_SUCCESS = 'GET_CASE_SUCCESS'

export const GET_CASES_FAIL = 'GET_CASES_FAIL'
export const GET_CASES_REQUEST = 'GET_CASES_REQUEST'
export const GET_CASES_SUCCESS = 'GET_CASES_SUCCESS'

export const GET_CASEDESC_FAIL = 'GET_CASEDESC_FAIL'
export const GET_CASEDESC_REQUEST = 'GET_CASEDESC_REQUEST'
export const GET_CASEDESC_SUCCESS = 'GET_CASEDESC_SUCCESS'

export const REF_CASES_FAIL = 'REF_CASES_FAIL'
export const REF_CASES_REQUEST = 'REF_CASES_REQUEST'
export const REF_CASES_SUCCESS = 'REF_CASES_SUCCESS'


export const GET_CITATION_FAIL = 'GET_CITATION_FAIL'
export const GET_CITATION_REQUEST = 'GET_CITATION_REQUEST'
export const GET_CITATION_SUCCESS = 'GET_CITATION_SUCCESS'

export const GET_CITATIONS_FAIL = 'GET_CITATIONS_FAIL'
export const GET_CITATIONS_REQUEST = 'GET_CITATIONS_REQUEST'
export const GET_CITATIONS_SUCCESS = 'GET_CITATIONS_SUCCESS'


export const GET_ORDINANCE_FAIL = 'GET_ORDINANCE_FAIL'
export const GET_ORDINANCE_REQUEST = 'GET_ORDINANCE_REQUEST'
export const GET_ORDINANCE_SUCCESS = 'GET_ORDINANCE_SUCCESS'

export const GET_STATUTE_FAIL = 'GET_STATUTE_FAIL'
export const GET_STATUTE_REQUEST = 'GET_STATUTE_REQUEST'
export const GET_STATUTE_SUCCESS = 'GET_STATUTE_SUCCESS'

export const GET_STATUTES_FAIL = 'GET_STATUTES_FAIL'
export const GET_STATUTES_REQUEST = 'GET_STATUTES_REQUEST'
export const GET_STATUTES_SUCCESS = 'GET_STATUTES_SUCCESS'

export const GET_STATUTEREAD_FAIL = 'GET_STATUTEREAD_FAIL'
export const GET_STATUTEREAD_REQUEST = 'GET_STATUTEREAD_REQUEST'
export const GET_STATUTEREAD_SUCCESS = 'GET_STATUTEREAD_SUCCESS'

export const REF_STATUTES_FAIL = 'REF_STATUTES_FAIL'
export const REF_STATUTES_REQUEST = 'REF_STATUTES_REQUEST'
export const REF_STATUTES_SUCCESS = 'REF_STATUTES_SUCCESS'

export const JOURNAL_NAMES_FAIL = 'JOURNAL_NAMES_FAIL'
export const JOURNAL_NAMES_REQUEST = 'JOURNAL_NAMES_REQUEST'
export const JOURNAL_NAMES_SUCCESS = 'JOURNAL_NAMES_SUCCESS'

export const CITATION_IDS_FAIL = 'CITATION_IDS_FAIL'
export const CITATION_IDS_REQUEST = 'CITATION_IDS_REQUEST'
export const CITATION_IDS_SUCCESS = 'CITATION_IDS_SUCCESS'