export const BOOKMARK_REQUEST = 'BOOKMARK_REQUEST'
export const BOOKMARK_SUCCESS = 'BOOKMARK_SUCCESS'
export const BOOKMARK_FAIL = 'BOOKMARK_FAIL'

export const GET_BOOKMARK_REQUEST = 'GET_BOOKMARK_REQUEST'
export const GET_BOOKMARK_SUCCESS = 'GET_BOOKMARK_SUCCESS'
export const GET_BOOKMARK_FAIL = 'GET_BOOKMARK_FAIL'

export const DELETE_BOOKMARK_REQUEST = 'DELETE_BOOKMARK_REQUEST'
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS'
export const DELETE_BOOKMARK_FAIL = 'DELETE_BOOKMARK_FAIL'

export const UPDATE_BOOKMARK_REQUEST = 'UPDATE_BOOKMARK_REQUEST'
export const UPDATE_BOOKMARK_SUCCESS = 'UPDATE_BOOKMARK_SUCCESS'
export const UPDATE_BOOKMARK_FAIL = 'UPDATE_BOOKMARK_FAIL'

export const GET_DICTIONARIES_FAIL = 'GET_DICTIONARIES_FAIL'
export const GET_DICTIONARIES_REQUEST = 'GET_DICTIONARIES_REQUEST'
export const GET_DICTIONARIES_SUCCESS = 'GET_DICTIONARIES_SUCCESS'

export const GET_DICTIONARY_FAIL = 'GET_DICTIONARY_FAIL'
export const GET_DICTIONARY_REQUEST = 'GET_DICTIONARY_REQUEST'
export const GET_DICTIONARY_SUCCESS = 'GET_DICTIONARY_SUCCESS'

export const GET_LEGALTERMS_FAIL = 'GET_LEGALTERMS_FAIL'
export const GET_LEGALTERMS_REQUEST = 'GET_LEGALTERMS_REQUEST'
export const GET_LEGALTERMS_SUCCESS = 'GET_LEGALTERMS_SUCCESS'

export const GET_LEGALTERM_FAIL = 'GET_LEGALTERM_FAIL'
export const GET_LEGALTERM_REQUEST = 'GET_LEGALTERM_REQUEST'
export const GET_LEGALTERM_SUCCESS = 'GET_LEGALTERM_SUCCESS'

export const GET_CASE_BY_LEGALTERM_FAIL = 'GET_CASE_BY_LEGALTERM_FAIL'
export const GET_CASE_BY_LEGALTERM_REQUEST = 'GET_CASE_BY_LEGALTERM_REQUEST'
export const GET_CASE_BY_LEGALTERM_SUCCESS = 'GET_CASE_BY_LEGALTERM_SUCCESS'

export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL'
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'

export const GET_ARTICLE_FAIL = 'GET_ARTICLE_FAIL'
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST'
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS'

export const SEARCH_ARTICLES_FAIL = 'SEARCH_ARTICLES_FAIL'
export const SEARCH_ARTICLES_REQUEST = 'SEARCH_ARTICLES_REQUEST'
export const SEARCH_ARTICLES_SUCCESS = 'SEARCH_ARTICLES_SUCCESS'

export const GET_TOPICS_FAIL = 'GET_TOPICS_FAIL'
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST'
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS'


export const TOPIC_STATUTES_FAIL = 'TOPIC_STATUTES_FAIL'
export const TOPIC_STATUTES_REQUEST = 'TOPIC_STATUTES_REQUEST'
export const TOPIC_STATUTES_SUCCESS = 'TOPIC_STATUTES_SUCCESS'