export const PACKAGE_REQUEST = 'PACKAGE_REQUEST'
export const PACKAGE_SUCCESS = 'PACKAGE_SUCCESS'
export const PACKAGE_FAIL = 'PACKAGE_FAIL'

export const CHOOSE_PACKAGE = 'CHOOSE_PACKAGE'

export const GET_PACKAGES_REQUEST = 'GET_PACKAGES_REQUEST'
export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS'
export const GET_PACKAGES_FAIL = 'GET_PACKAGES_FAIL'

export const DELETE_PACKAGE_REQUEST = 'DELETE_PACKAGE_REQUEST'
export const DELETE_PACKAGE_SUCCESS = 'DELETE_PACKAGE_SUCCESS'
export const DELETE_PACKAGE_FAIL = 'DELETE_PACKAGE_FAIL'

export const UPDATE_PACKAGE_REQUEST = 'UPDATE_PACKAGE_REQUEST'
export const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS'
export const UPDATE_PACKAGE_FAIL = 'UPDATE_PACKAGE_FAIL'

export const GET_PACKAGE_REQUEST = 'GET_PACKAGE_REQUEST'
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS'
export const GET_PACKAGE_FAIL = 'GET_PACKAGE_FAIL'