export const PAYMENT_REQUEST = 'PAYMENT_REQUEST'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'
export const PAYMENT_FAIL = 'PAYMENT_FAIL'

export const SEARCH_PAYMENTS_REQUEST = 'SEARCH_PAYMENTS_REQUEST'
export const SEARCH_PAYMENTS_SUCCESS = 'SEARCH_PAYMENTS_SUCCESS'
export const SEARCH_PAYMENTS_FAIL = 'SEARCH_PAYMENTS_FAIL'

export const GET_PAYMENTS_REQUEST = 'GET_PAYMENTS_REQUEST'
export const GET_PAYMENTS_SUCCESS = 'GET_PAYMENTS_SUCCESS'
export const GET_PAYMENTS_FAIL = 'GET_PAYMENTS_FAIL'

export const DELETE_PAYMENT_REQUEST = 'DELETE_PAYMENT_REQUEST'
export const DELETE_PAYMENT_SUCCESS = 'DELETE_PAYMENT_SUCCESS'
export const DELETE_PAYMENT_FAIL = 'DELETE_PAYMENT_FAIL'

export const UPDATE_PAYMENT_REQUEST = 'UPDATE_PAYMENT_REQUEST'
export const UPDATE_PAYMENT_SUCCESS = 'UPDATE_PAYMENT_SUCCESS'
export const UPDATE_PAYMENT_FAIL = 'UPDATE_PAYMENT_FAIL'

export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST'
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS'
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL'