
export const SEARCH_CASE_FAIL = 'SEARCH_CASE_FAIL'
export const SEARCH_CASE_REQUEST= 'SEARCH_CASE_REQUEST'
export const SEARCH_CASE_SUCCESS= 'SEARCH_CASE_SUCCESS'

export const SEARCH_INDEX_FAIL = 'SEARCH_INDEX_FAIL'
export const SEARCH_INDEX_REQUEST = 'SEARCH_INDEX_REQUEST'
export const SEARCH_INDEX_SUCCESS = 'SEARCH_INDEX_SUCCESS'

export const SEARCH_CITATION_FAIL = 'SEARCH_CITATION_FAIL'
export const SEARCH_CITATION_REQUEST = 'SEARCH_CITATION_REQUEST'
export const SEARCH_CITATION_SUCCESS = 'SEARCH_CITATION_SUCCESS'

export const SEARCH_COURT_FAIL = 'SEARCH_COURT_FAIL'
export const SEARCH_COURT_REQUEST = 'SEARCH_COURT_REQUEST'
export const SEARCH_COURT_SUCCESS = 'SEARCH_COURT_SUCCESS'

export const SEARCH_ADVANCE_FAIL = 'SEARCH_ADVANCE_FAIL'
export const SEARCH_ADVANCE_REQUEST = 'SEARCH_ADVANCE_REQUEST'
export const SEARCH_ADVANCE_SUCCESS = 'SEARCH_ADVANCE_SUCCESS'