
export const STATUTES_DATA_FAIL = 'STATUTES_DATA_FAIL'
export const STATUTES_DATA_REQUEST = 'STATUTES_DATA_REQUEST'
export const STATUTES_DATA_SUCCESS = 'STATUTES_DATA_SUCCESS'

export const CASES_DATA_FAIL = 'CASES_DATA_FAIL'
export const CASES_DATA_REQUEST = 'CASES_DATA_REQUEST'
export const CASES_DATA_SUCCESS = 'CASES_DATA_SUCCESS'

export const LEGALTERMS_DATA_FAIL = 'LEGALTERMS_DATA_FAIL'
export const LEGALTERMS_DATA_REQUEST = 'LEGALTERMS_DATA_REQUEST'
export const LEGALTERMS_DATA_SUCCESS = 'LEGALTERMS_DATA_SUCCESS'

export const ARTICLES_DATA_FAIL = 'ARTICLES_DATA_FAIL'
export const ARTICLES_DATA_REQUEST = 'ARTICLES_DATA_REQUEST'
export const ARTICLES_DATA_SUCCESS = 'ARTICLES_DATA_SUCCESS'

export const TOPICS_DATA_FAIL = 'TOPICS_DATA_FAIL'
export const TOPICS_DATA_REQUEST = 'TOPICS_DATA_REQUEST'
export const TOPICS_DATA_SUCCESS = 'TOPICS_DATA_SUCCESS'

export const DICTIONARY_DATA_FAIL = 'DICTIONARY_DATA_FAIL'
export const DICTIONARY_DATA_REQUEST = 'DICTIONARY_DATA_REQUEST'
export const DICTIONARY_DATA_SUCCESS = 'DICTIONARY_DATA_SUCCESS'